RefugioAnimal/Controllers/AboutUsController.cs
using Microsoft.AspNetCore.Mvc;

namespace RefugioAnimal.Controllers
{
    public class AboutUsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

RefugioAnimal/Controllers/AnimalController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RefugioAnimal.Models;
using RefugioAnimal.Models.Enums;
using RefugioAnimal.Services;

namespace RefugioAnimal.Controllers
{
    public class AnimalController : Controller
    {
        private readonly AnimalService _animalService;

        public AnimalController(AnimalService animalService)
        {
            _animalService = animalService;
        }

        public async Task<IActionResult> Index()
        {
            var cats = await _animalService.GetAnimalsBySpecieAsync(Species.Cat, 4, 0);
            var dogs = await _animalService.GetAnimalsBySpecieAsync(Species.Dog, 8, 0);
            var adoptedAnimals = await _animalService.GetAdoptedAnimalsAsync(4);
            var randomAnimal = await _animalService.GetRandomAnimalAsync(null);

            var viewModel = new AnimalViewModel
            {
                Cats = cats,
                Dogs = dogs,
                AdoptedAnimals = adoptedAnimals,
                RandomAnimal = randomAnimal
            };

            return View(viewModel);
        }

        public async Task<IActionResult> Cats()
        {
            var cats = await _animalService.GetAnimalsBySpecieAsync(Species.Cat, 24, 0);

            var viewModel = new CatsViewModel
            {
                Cats = cats
            };

            return View(viewModel);
        }

        public async Task<IActionResult> Dogs()
        {
            var dogs = await _animalService.GetAnimalsBySpecieAsync(Species.Dog, 24, 0);

            var viewModel = new DogsViewModel
            {
                Dogs = dogs
            };

            return View(viewModel);
        }

        public async Task<IActionResult> AnimalSpecies()
        {
            var cats = await _animalService.GetAnimalsBySpecieAsync(Species.Cat, 1, 0);
            var dogs = await _animalService.GetAnimalsBySpecieAsync(Species.Dog, 1, 0);

            var viewModel = new AnimalSpeciesViewModel
            {
                Cats = cats,
                Dogs = dogs
            };

            return View(viewModel);
        }

        public async Task<IActionResult> AnimalProfile(long animalId)
        {
            var animal = await _animalService.GetAnimalByIdAsync(animalId);

            if (animal == null)
            {
                return NotFound();
            }

            var viewModel = new AnimalProfileViewModel
            {
                Animal = animal
            };

            return View(viewModel);

        }
    }
}

RefugioAnimal/Controllers/NGOController.cs
using Microsoft.AspNetCore.Mvc;

namespace RefugioAnimal.Controllers
{
    public class NGOController : Controller
    {
        public IActionResult NGOAndProtector()
        {
            return View();
        }

        public IActionResult Donations()
        {
            return View();
        }
    }
}

RefugioAnimal/Views/Shared/_AccountLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/account.css" asp-append-version="true" />
    @RenderSection("Styles", required: false)
</head>
<body>

    @* Espaço do componente renderizado *@
    <div>
        @RenderBody()
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/layout.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RefugioAnimal/Views/Shared/_AnimalList.cshtml
@model IEnumerable<RefugioAnimal.Models.DTOs.AnimalDto>
@{
    var maxItems = ViewData["MaxItems"] as int? ?? int.MaxValue;
    var limitedModel = Model.Take(maxItems);
}

@if (limitedModel.Any())
{
    @foreach (var item in limitedModel)
    {
        <div class="col-sm-6 col-md-4 col-lg-3 mb-4">
            <div class="card" onclick="location.href='@Url.Action("AnimalProfile", "Animal", new { animalId = item.Id })';" style="cursor: pointer;">
                <div class="card-img-container">
                    @if (item.Photos != null && item.Photos.Count > 0)
                    {
                        <img src="@item.Photos.First()" class="card-img-top" alt="Imagem">
                    }
                </div>
                <div class="card-overlay">
                    <h5 class="card-title">@item.Name</h5>
                    <p class="card-text">@item.Description</p>
                </div>
            </div>
        </div>
    }
}
else
{
    <p class="text-center">Nenhum animal encontrado.</p>
}

RefugioAnimal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Refúgio Animal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RefugioAnimal.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/layout.css" asp-append-version="true" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <div class="d-flex align-items-center">
                    <img class="logo me-2" src="/assets/logo.svg" alt="Logo" />
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Refúgio Animal</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>

                <div class="collapse navbar-collapse justify-content-center" id="navbarContent">
                    <ul class="navbar-nav justify-content-between">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Animal" asp-action="Index">Encontre O Seu Animal</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Animal" asp-action="AnimalSpecies">Espécies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NGO" asp-action="NGOAndProtector">ONGs/Protetores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NGO" asp-action="Donations">Doações</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AboutUs" asp-action="Index">Sobre Nós</a>
                        </li>
                        <partial name="_LoginPartial" />
                    </ul>
                </div>

                <div class="d-flex align-items-center">
                    <input class="form-control me-2 search" type="search" id="search" placeholder="Buscar..." aria-label="Search">
                </div>
            </div>
        </nav>
    </header>


    @* Espaço do componente renderizado *@
    <div class="container">
        <main role="main" class="pb-3 content">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Refúgio Animal
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/layout.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>